aventus_machine_test/aventus_machine_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('string_check/', include('string_check.urls')),
    path('admin/', admin.site.urls),
]

aventus_machine_test/string_check/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

aventus_machine_test/string_check/models.py
from django.db import models

# Create your models here.

aventus_machine_test/string_check/forms.py
from django import forms

class SimpleForm(forms.Form):
		master_string = forms.CharField(
		    label='Master String'
		)
		string_1 = forms.CharField(
		    label='String 1'
		)
		string_2 = forms.CharField(
		    label='String 2'
		)
		string_3 = forms.CharField(
		    label='String 3'
		)
		string_4 = forms.CharField(
		    label='String 4'
		)

aventus_machine_test/string_check/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render
from .forms import SimpleForm

def index(request):
	if request.method == 'GET':
		form = SimpleForm()
		return render(request, 'string_check/index.html', {"form": form})
	elif request.method == 'POST':
		try:
			strings_req =json.loads(request.POST.get('strings'))	
			form = SimpleForm(strings_req)

			if form.is_valid():
				master_string = form.cleaned_data['master_string'].lower()
				string_1 = form.cleaned_data['string_1'].lower()
				string_2 = form.cleaned_data['string_2'].lower()
				string_3 = form.cleaned_data['string_3'].lower()
				string_4 = form.cleaned_data['string_4'].lower()
				
				master_str_list = list(master_string)
				stings_list = [string_1, string_2, string_3, string_4]

				result_dict_string = {}

				for each_str in stings_list:
					temp_list = []
					for each_chr in each_str:
						if each_chr in master_str_list:
							master_str_list.remove(each_chr)
							temp_list.append(each_chr)
							continue
					if(len(each_str) == len(temp_list)):
						result_dict_string[each_str] = "yes"
					else:
						result_dict_string[each_str] = "no"
				return JsonResponse({"result":result_dict_string, "status": "success"})
			else:
				return JsonResponse({"reason":"form not valid", "status": "not valid"})
		except Exception as e:
			return JsonResponse({"reason":str(e), "status": "not success"})		

aventus_machine_test/string_check/templates/string_check/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Aventus machine test</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
	<form id="the_string_form" method="POST" action="">
		{% csrf_token %}
		{% for field in form %}
			<label>{{ field.label }}</label>
			{{field}}</br>
		{% endfor %}
		<br/><input type="submit" value="Submit">
	</form>	
	<p id="error_msg" style="display: none;color: red">* Error on server</p>
	<br/><br/>
	<div id="string_check_result_div" style="display: none;">
	  <head><b>Result</b></head>
	  <p>****************</p>	
	  <table id="string_check_result">
	    <thead>
		    <tr>
		      <th>Strings</th>
		      <th>Status</th>
		    </tr>
	    </thead>
	    <tbody>
	    </tbody>
	  </table>
	</div>	
</body>
<script type="text/javascript">

	$('#the_string_form').on('submit', function(event){
	    event.preventDefault();
	    $("#error_msg").hide();
	    $('#string_check_result tbody tr').remove();
	    $("#string_check_result_div").hide();
	    $.ajax({
	            url : "", // the endpoint
	            type : "POST", // http method
	            data : { "strings" : JSON.stringify({
	            "master_string": $("#id_master_string").val(), 
	            "string_1": $("#id_string_1").val(),
	            "string_2": $("#id_string_2").val(),
	            "string_3": $("#id_string_3").val(),
	            "string_4": $("#id_string_4").val(),
	            }), 'csrfmiddlewaretoken': '{{ csrf_token }}' }, // data sent with the post request

	            // handle a successful response
	            success : function(data) {
	            	console.log(data)
	            	if(data["status"] == "success") {
	            		for(let each in data["result"]){
	            			$('#string_check_result tbody').append('<tr>\
	            				<td>'+each+'</td>\
	            				<td>'+data['result'][each]+'</td>\
	            				</tr>');
	            		}
	            		$("#string_check_result_div").show();
	            	}
	            	else {
	            		$("#error_msg").show();
	            	}
	            }
	    });        
	});

</script>
</html>